return {
  ["workshop-1111658995"]={ configuration_options={  }, enabled=true },
  ["workshop-1185229307"]={
    configuration_options={
      [""]="",
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      HORIZONTAL_OFFSET=0,
      NOEPIC=false,
      NONOEPIC=false,
      WETNESS_METER=false 
    },
    enabled=true 
  },
  ["workshop-1894295075"]={ configuration_options={  }, enabled=true },
  ["workshop-2528541304"]={
    configuration_options={ amount_given=4, amount_given2=4, planting_floor=true },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-466732225"]={ configuration_options={  }, enabled=true },
  ["workshop-926178831"]={
    configuration_options={
      BATCLOISTER="OFF",
      BEFRIENDTHEPIGS="OFF",
      CAVEJUNGLE="OFF",
      CAVESWAMP="OFF",
      FROGSANDBUGS="OFF",
      FUNGALNOISEFOREST="OFF",
      FUNGALNOISEMEADOW="OFF",
      KILLERBEES="OFF",
      KILLTHESPIDERS="OFF",
      MAGICMEADOW="OFF",
      MAKEABEEHAT="OFF",
      MILITARYPITS="OFF",
      MOLECOLONYDECIDUOUS="OFF",
      MOLECOLONYROCKS="OFF",
      MOOSEBREEDINGTASK="OFF",
      MOREALTARS="OFF",
      MUDDYSACRED="OFF",
      PLEASANTSINKHOLE="OFF",
      RABBITCITY="OFF",
      RABBITSPIDERWAR="OFF",
      RABBITTOWN="OFF",
      RESIDENTIAL2="OFF",
      RESIDENTIAL3="OFF",
      SACREDDANGER="OFF",
      SPIDERLAND="OFF",
      SWAMPYSINKHOLE="OFF",
      THEHUNTERS="ON",
      UNDERGROUNDFOREST="OFF",
      null=0 
    },
    enabled=true 
  } 
}