return {
  ["workshop-1111658995"]={ configuration_options={  }, enabled=true },
  ["workshop-1185229307"]={
    configuration_options={
      [""]="",
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      HORIZONTAL_OFFSET=0,
      NOEPIC=false,
      NONOEPIC=false,
      WETNESS_METER=false 
    },
    enabled=true 
  },
  ["workshop-1894295075"]={ configuration_options={  }, enabled=true },
  ["workshop-2477889104"]={
    configuration_options={
      BADGE_BG_BRIGHTNESS=60,
      BADGE_BG_OPACITY=100,
      COLOR_DOMESTICATION_DEFAULT="WHITE",
      COLOR_DOMESTICATION_ORNERY="ORANGE",
      COLOR_DOMESTICATION_PUDGY="PURPLE",
      COLOR_DOMESTICATION_RIDER="BLUE",
      COLOR_OBEDIENCE="RED",
      COLOR_TIMER="GREEN",
      ClientConfig=false,
      EnableSounds=false,
      GapModifier=0,
      HEALTH_BADGE_CLEAR_BG=false,
      HungerThreshold=10,
      OffsetX=0,
      OffsetXFine=0,
      OffsetXMult=1,
      OffsetY=0,
      OffsetYFine=0,
      OffsetYMult=1,
      SEPARATOR_BADGE_COLORS=1,
      SEPARATOR_BADGE_SETTINGS=1,
      SEPARATOR_GENERAL=1,
      SEPARATOR_POSITIONING_X=1,
      SEPARATOR_POSITIONING_Y=1,
      Scale=1,
      ShowByDefault=true,
      Theme="Default",
      ToggleKey="KEY_T" 
    },
    enabled=true 
  },
  ["workshop-2528541304"]={
    configuration_options={ amount_given=4, amount_given2=4, planting_floor=true },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-466732225"]={ configuration_options={  }, enabled=true },
  ["workshop-786654500"]={ configuration_options={ active=true }, enabled=true },
  ["workshop-926178831"]={
    configuration_options={
      BATCLOISTER="OFF",
      BEFRIENDTHEPIGS="OFF",
      CAVEJUNGLE="OFF",
      CAVESWAMP="OFF",
      FROGSANDBUGS="OFF",
      FUNGALNOISEFOREST="OFF",
      FUNGALNOISEMEADOW="OFF",
      KILLERBEES="OFF",
      KILLTHESPIDERS="OFF",
      MAGICMEADOW="OFF",
      MAKEABEEHAT="OFF",
      MILITARYPITS="OFF",
      MOLECOLONYDECIDUOUS="OFF",
      MOLECOLONYROCKS="OFF",
      MOOSEBREEDINGTASK="OFF",
      MOREALTARS="OFF",
      MUDDYSACRED="OFF",
      PLEASANTSINKHOLE="OFF",
      RABBITCITY="OFF",
      RABBITSPIDERWAR="OFF",
      RABBITTOWN="OFF",
      RESIDENTIAL2="OFF",
      RESIDENTIAL3="OFF",
      SACREDDANGER="OFF",
      SPIDERLAND="OFF",
      SWAMPYSINKHOLE="OFF",
      THEHUNTERS="ON",
      UNDERGROUNDFOREST="OFF",
      null=0 
    },
    enabled=true 
  } 
}